config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/:category', to: 'tops#index'
  root 'tops#index'
  post 'map', to: 'tops#go_to_list'
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
        if params[:category] then
            category = params[:category]
            @images = Image.where(category:category)
        else
            @images = Image.all
        end
        gon.insta_access_token = ENV['INSTA_ACCESS_TOKEN']
        gon.insta_business_id = ENV['INSTA_BUSINESSID']
    end

    def go_to_list
        images = params[:go_image_name].keys
        dir_url =  'https://www.google.co.jp/maps/dir/?api=1&dir_action=navigate&waypoints='
        images.each_with_index do |image, index|
            if index == images.size - 1 then
                dir_url = dir_url + '&destination=' + image
            else
                dir_url = dir_url + image + '|'
            end
        end
        redirect_to(dir_url)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>musubun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/x-icon" href="enmusubi.png">
    <meta name="google-site-verification" content="7QBj1RirqxJ9g4PvnX1Q5gbUlQ6Vc6rjcO276p3tfV0" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
<!-- jQuery読み込み -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- bulmaのnavbar desktop -->
<nav class="navbar is-warning is-fixed-top is-hidden-touch" role="navigation" aria-label="main navigation">
   <div class="navbar-brand is-hiddent-touch">
     <a class="navbar-item" href="/">
     <img src="musubun.png" class="musubun">
     </a>
   </div>


<div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item all is-hidden-touch">
        All
      </a>
      <a class="navbar-item view is-hidden-touch">
        景色
      </a>
      <a class="navbar-item food is-hidden-touch">
        食べ物
      </a>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <button type="submit" form="go_button" id="btn2" class="button is-info" disabled>
            <span style="font-size: 30px">
            <strong>Go!→</strong>
            </span>
          </button>
        </div>
      </div>
    </div>
  </div>
</nav>
<!-- /bulmaのnavbar -->
<!-- bulmaのnavbar touch -->
<nav class="navbar is-warning is-fixed-top is-hidden-desktop" role="navigation" aria-label="main navigation">
  <div class="navbar-brand is-hidden-desktop">
    <a class="navbar-item" href="/">
    <img src="musubun.png" class="is-hidden-desktop musubun">
    </a>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" style="height: 150px; width: 150px">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item all is-hidden-desktop">
        All
      </a>
      <a class="navbar-item view is-hidden-desktop">
        景色
      </a>
      <a class="navbar-item food is-hidden-desktop">
        食べ物
      </a>
    </div>
  </div>
</nav>
<!-- /bulmaのnavbar -->

<div class="items">
<%= form_with(url: map_path, local: true, id: "go_button") do |f| %>
<div class="container">
    <% @images.each do |image| %>
        <div class="item column is-half is-one-quarter-desktop", id= <%= "#{image.category}" %> >
            <%= image_tag("/#{image.image_path}",:class => "thumbnail")%>
            <%= check_box_tag "go_image_name[#{ image.place_name }]", image.place_name , false ,class:'disabled_checkbox'%>
        </div><br>
    <% end %>
</div>
<div class="is-fab has-content-centered is-hidden-desktop">
    <button type="submit" id="btn1" class="button btn-circle-stitch is-resize" disabled>
      <span>Go!</span>
  </button>
</div>

<% end %>
</div>

<script>
$(document).on('turbolinks:load', function() {
  //1回だけリロードさせる
  if (window.name != "any") {
    location.reload();
    window.name = "any";
  } else {
    window.name = "";
  }
  // チェックボックスのクリックを無効化します。
  $('.item .disabled_checkbox').click(function() {
    return false;
  });

  // 画像がクリックされた時の処理です。
  $('img.thumbnail').click(function() {
    $(this).toggleClass("checked");//クラスにcheckedを追加
    var nextCheckbox = $(this).next();//クリックした画像についているチェックボックスだけを変数に入れた
    
    if ($(nextCheckbox).prop('checked')) { //その画像にチェックが入っていたら
 
      // チェックを外す
      $(nextCheckbox).prop('checked', false);
 
    // もしチェックが外れていたら
    } else {
 
      // チェックを入れる
      $(nextCheckbox).prop('checked', true);
    }
        if ($("img.thumbnail.checked").length > 0) { //チェックした画像が1枚以上あれば
            // ボタン有効
            $("#btn1").prop("disabled", false);
            $("#btn2").prop("disabled", false);
        } else {
          // 画像をチェックしてないならばボタン無効
          $("#btn1").prop("disabled", true);
          $("#btn2").prop("disabled", true);
        }
  });
});

$(function() {
 
  // 食べ物ボタンをクリックしたら発動
  $('.navbar-item.food').click(function() {
    $(".item").removeClass('behind') //全部の画像からclass　behindを削除してから
    $("#view.item").addClass('behind');　//景色の写真だけにclass behindを追加
  });

  // 景色ボタンをクリックしたら発動
  $('.navbar-item.view').click(function() {
    $(".item").removeClass('behind')//全部の画像からclass　behindを削除してから
    $("#food.item").addClass('behind');//食べ物の写真だけにclass behindを追加
    });

  // ALLボタンをクリックしたら発動
  $('.navbar-item.all').click(function() {
    $(".item").removeClass('behind');//全部の画像からclass　behindを削除してから全表示
  });
});

$(document).ready(function() {

    // Check for click events on the navbar burger icon
   $(".navbar-burger").click(function() {

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
       $(".navbar-burger").toggleClass("is-active");
       $(".navbar-menu").toggleClass("is-active");

    });
 });
</script>